AM-Inspire-Devfit/devfit-server

build.gradle, src/main/resources/application.yml
- close #8 
---
- /devfit-actuator/health로 헬스 체크를 할 수 있습니다.
- actuator 보안 설정을 추가하였습니다.
- 기본적으로 모든 엔드포인트를 비활성화했습니다. (enabled-by-default는 deprecated로 인해 access-default)
- health 엔드포인트만 활성화했습니다.
- JMX 엔드포인트는 모두 비활성화하고, health 엔드포인트만 노출하도록 설정했습니다.
- actuator 기본 경로를 /devfit-actuator/health로 변경하였습니다.
---
- https://techblog.woowahan.com/9232/
- https://github.com/spring-projects/spring-boot/issues/43302
=> chore: Spring Boot Actuator 설정

.github/workflows/develop_build_deploy.yml, .gitignore, build.gradle, docker-compose-test.yml, docker-compose.yml, src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java, src/main/java/com/amcamp/infra/config/redis/RedisConfig.java, src/main/java/com/amcamp/infra/config/redis/RedisProperties.java, src/main/resources/application.yml, src/test/java/com/amcamp/DevFitApplicationTests.java, src/test/resources/application-test.yml
- close #18 
---
- Redis Config 생성
- Redis 연결 설정을 application.yml에 추가
- 테스트 환경에서 독립된 Redis를 사용하기 위해 docker-compose-test.yml을 추가하고 빌드 과정에서 사용
- SpringBootTest에서 @ActiveProfiles을 통해 test profile을 사용하도록 설정
- Docker Compose를 사용해 Redis 컨테이너를 설정하고 backend 서비스와 동일 네트워크로 구성
=> chore: Redis 설정

build.gradle, src/main/resources/application-actuator.yml, src/main/resources/application-datasource.yml, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application-redis.yml, src/main/resources/application.yml, src/test/resources/application-test.yml
- close #24 
---
- application.yml을 환경 별로 분리하였습니다.
- 로컬, 개발, 테스트 환경별 설정을 그룹화하였습니다.
- 모든 환경에서 공통으로 사용하는 설정을 include로 관리합니다.
- 로컬 환경은 h2 db를, 개발 환경은 RDS (MySQL)를 사용하도록 설정하였습니다.
=> chore: application.yml 환경 분리 및 DB 설정

src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
- close #35 
---
- Swagger에서 JWT 인증을 위한 Authorization 헤더를 추가하였습니다.
- Authorization 헤더에 액세스 토큰 값을 추가하여 저장하면 이후의 요청에 자동으로 해당 토큰이 포함되도록 설정하였습니다.
=> feat: Swagger UI에 Authorization 헤더 추가

docker-compose.yml
- close #37 
---
- 도커 컨테이너에서 실행되는 서버의 Timezone을 Asia/Seoul로 변경하였습니다.
---
- 로컬 스프링부트 서버
<br/>
- 도커 컨테이너 스프링부트 서버
=> fix: Docker Container Timezone 설정

src/main/java/com/amcamp/domain/auth/dto/request/AuthCodeRequest.java, src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadCompleteRequest.java, src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadRequest.java, src/main/java/com/amcamp/domain/member/dto/request/NicknameUpdateRequest.java, src/main/java/com/amcamp/global/exception/ErrorResponse.java, src/main/java/com/amcamp/global/exception/GlobalExceptionHandler.java, src/main/java/com/amcamp/global/exception/errorcode/GlobalErrorCode.java, src/test/java/com/amcamp/global/exception/ExceptionHandlerTest.java
- close #54 
---
- MethodArgumentNotValidException 처리
- @Valid로 인해 유효성 검사에서 발생한 오류를 처리하여 클라이언트 요청이 잘못되었을 때 400 Bad Request를 반환합니다.
- Internal Server Error 처리
- 서버에서 예상치 못한 오류가 발생했을 때 500번 오류와 관련된 예외를 처리하여 클라이언트에게 적절한 응답을 반환합니다.
=> chore: Validation 및 Internal Server Error 처리

src/main/java/com/amcamp/domain/member/api/MemberController.java, src/main/java/com/amcamp/domain/member/application/MemberService.java, src/main/java/com/amcamp/domain/member/dto/response/MemberInfoResponse.java, src/test/java/com/amcamp/domain/member/application/MemberServiceTest.java
- close #49 
---
- 회원 정보 조회 기능을 구현하였습니다.
- 조회 API의 경우 서비스 레이어에서 Transactional(readOnly = true) 추가하시기 바랍니다.
- Response DTO의 경우 정적 팩토리 메서드 from을 적용하였습니다.
---
- DTO에서 사용하는 정적 팩토리 메서드 of나 from 사용을 권장드립니다!
=> feat: 회원 정보 조회

src/main/java/com/amcamp/domain/member/api/MemberController.java, src/main/java/com/amcamp/domain/member/application/MemberService.java, src/test/java/com/amcamp/domain/member/application/MemberServiceTest.java
- close #48 
---
- 회원의 로그아웃 기능을 구현하였습니다.
- 회원탈퇴와 동일하게 로그아웃 시 Redis에 저장되어 있는 리프레시 토큰과 쿠키에 담긴 토큰이 삭제됩니다.
=> feat: 로그아웃 구현

src/main/java/com/amcamp/domain/participant/dao/ParticipantRepository.java, src/main/java/com/amcamp/domain/team/api/TeamController.java, src/main/java/com/amcamp/domain/team/application/TeamService.java, src/main/java/com/amcamp/domain/team/domain/Team.java, src/main/java/com/amcamp/domain/team/dto/request/TeamCreateRequest.java, src/main/java/com/amcamp/domain/team/dto/request/TeamInviteCodeRequest.java, src/main/java/com/amcamp/domain/team/dto/request/TeamUpdateRequest.java, src/main/java/com/amcamp/domain/team/dto/response/TeamCheckResponse.java, src/main/java/com/amcamp/domain/team/dto/response/TeamInfoResponse.java, src/main/java/com/amcamp/global/exception/errorcode/TeamErrorCode.java, src/main/java/com/amcamp/global/util/RedisUtil.java, src/test/java/com/amcamp/domain/team/TeamServiceTest.java
- close #46 
---
- 팀 수정 및 삭제 기능을 구현했습니다.
- 팀 수정 시 Validation 규칙에 따라 팀 이름은 팀이름 필드 삭제, null, "" 중 어떠한 경우도 허용되지 않으나, 팀 설명은 모두 허용됩니다. 
- 팀 기본 정보 조회 기능을 구현했습니다.
- 팀 정보(Info)응답은 팀 스페이스 화면에 표시되는 팀 이름, 팀 설명 필드를 담아 반환합니다.
- 이 응답은 초대 코드 입력 후 팀 이름을 반환하는 팀 확인(Check)응답과 구분됩니다.
- 팀 참여자에 해당되는 회원만 <코드 확인>, <팀 수정>, <팀 삭제>, <팀 정보>에 접근 가능하도록 권한을 수정하였습니다.
- 특히 <팀 수정>과 <팀 삭제>의 경우 팀 관리자만 접근할 수 있도록 권한을 부여하였습니다. 
---
=> feat: 팀 수정, 팀 삭제, 팀 기본 정보 조회 기능 구현

src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadCompleteRequest.java, src/main/java/com/amcamp/domain/image/dto/request/MemberImageUploadRequest.java
- close #63 
---
- Enum 타입의 경우 Validation으로 NotBlank 어노테이션 사용 시 UnexpectedTypeException이 발생합니다.
- NotBlank의 경우 String 타입에만 쓰시고 나머지는 NotNull 사용하시기 바랍니다!
=> fix: 이미지 API UnexpectedTypeException으로 인한 Validate 수정

src/main/java/com/amcamp/domain/team/api/TeamController.java, src/main/java/com/amcamp/domain/team/application/TeamService.java, src/main/java/com/amcamp/domain/team/domain/Team.java, src/main/java/com/amcamp/domain/team/dto/request/TeamEmojiUpdateRequest.java, src/main/java/com/amcamp/domain/team/dto/response/TeamInfoResponse.java, src/test/java/com/amcamp/domain/team/TeamServiceTest.java
- close #62  
---
- 팀 도메인에 이모지를 추가하면서 변경되는 사항을 수정했습니다.
- 팀 생성 시 자동으로 기본 이모지인 "🍇"가 부여됩니다.
- 팀 수정과 팀 이모지 수정 컨트롤러/서비스 메소드와 요청 DTO를 구분하였습니다.
- 반면 반환값은 TeamInfoResponse으로 통일하여 팀 상단에 위치하는 주요 정보를 한번에 전달 받을 수 있도록 했습니다.
---
=> feat: 팀 도메인에 이모지 추가

src/main/java/com/amcamp/domain/team/api/TeamController.java, src/main/java/com/amcamp/domain/team/application/TeamService.java, src/main/java/com/amcamp/domain/team/dao/TeamRepository.java, src/main/java/com/amcamp/domain/team/dao/TeamRepositoryCustom.java, src/main/java/com/amcamp/domain/team/dao/TeamRepositoryImpl.java, src/main/java/com/amcamp/domain/team/domain/Team.java, src/main/java/com/amcamp/domain/team/dto/request/TeamCreateRequest.java, src/main/java/com/amcamp/domain/team/dto/response/TeamInfoResponse.java, src/main/java/com/amcamp/global/exception/errorcode/TeamErrorCode.java, src/test/java/com/amcamp/domain/team/TeamServiceTest.java
- close #60
---
- 회원이 참여한 팀 목록 조회 API를 구현하였습니다.
- TeamRepositoryCustom이라는 interface를 만들고 구현체로 TeamRepositoryImpl 클래스를 정의하였습니다.
- TeamRepository에서 JpaRepository와 TeamRepositoryCustom를 상속받기에 조회 메서드 또한 TeamRepository에서 호출합니다.
- 구현체에서 Slice와 QueryDSL을 사용하여 페이징 기능을 구현하였습니다.
- 팀에 참가한 날짜를 기준으로 내림차순하였고 No-Offset 방식으로 페이징 쿼리의 성능을 향상시켰습니다.
=> feat: 회원이 참여한 팀 목록 조회

src/main/java/com/amcamp/domain/image/application/ImageService.java, src/main/java/com/amcamp/global/config/scheduler/SchedulerConfig.java, src/main/java/com/amcamp/infra/scheduler/ImageCleanupScheduler.java
- close #65 
---
- 이미지 더미 데이터를 일정 주기마다 삭제하는 스케줄러를 추가하였습니다.
- 회원의 이미지가 변경되고 사용되지 않는 이미지 더미 데이터 처리를 위해 적용하였습니다.
- 자정마다 이미지 테이블에 있는 모든 데이터를 삭제합니다.
=> feat: 이미지 삭제 스케줄러 추가

src/main/java/com/amcamp/domain/auth/api/AuthController.java, src/main/java/com/amcamp/domain/image/api/ImageController.java, src/main/java/com/amcamp/domain/member/api/MemberController.java, src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/team/api/TeamController.java, src/main/resources/application.yml
- close #88 
---
- spring-doc 설정
- tags-sorter: alpha 및 operations-sorter: method 설정 추가하여 API 정렬 방식 개선
- Swagger 기본 URL 비활성화 및 doc-expansion: none 설정 적용
- Tag의 name 필드 수정
- API 그룹에 숫자 프리픽스(1-1. 등)를 추가하여 원하는 순서대로 정렬되도록 변경
---
=> refactor: Swagger API 목록 정렬

src/main/java/com/amcamp/domain/project/domain/ToDoInfo.java, src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintBasicUpdateRequest.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintToDoUpdateRequest.java, src/main/java/com/amcamp/domain/sprint/dto/response/SprintInfoResponse.java, src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java
- close #84 
---
- 스프린트 수정 기능
- 스프린트 기본 정보 수정
- 스프린트의 제목과 목표를 수정할 수 있습니다.
- 요청 시 두 필드는 필수값이 아니며 둘 중 하나만 포함해도 됩니다.
- 스프린트 일정 및 진행 상태 수정
- 스프린트의 시작 일자, 마감 일자, 진행 상태를 수정할 수 있습니다.
- 요청 시 모든 필드는 선택 사항이며 일정만 수정하거나 진행 상태만 수정할 수도 있습니다.
- 단, 시작 일자만 수정하는 경우 마감 일자보다 이후일 경우 에러가 발생하도록 처리하였습니다.
- 스프린트 삭제 기능
- 스프린트 삭제 시 연관된 태스크 정보 또한 모두 삭제됩니다.
---
- 테스트 코드의 경우 이슈 따로 파서 진행하겠습니다.
=> feat: 스프린트 수정, 삭제 기능 구현

src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java, src/main/java/com/amcamp/domain/sprint/dto/response/SprintInfoResponse.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
- close #98
---
- 프로젝트별 스프린트 목록 조회 기능을 구현하였습니다.
- 페이지당 하나의 스프린트만 가져오므로 pageSize를 1로 고정하였습니다. 
- sprintId를 기준으로 오름차순으로 정렬하였습니다.
=> feat: 프로젝트별 스프린트 목록 조회

src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java, src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java, src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepository.java, src/main/java/com/amcamp/domain/feedback/domain/Feedback.java, src/main/java/com/amcamp/domain/feedback/dto/request/FeedbackSendRequest.java, src/main/java/com/amcamp/global/exception/errorcode/FeedbackErrorCode.java, src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
- close #111 
---
- 사용자가 AI를 통해 개선한 피드백을 특정 팀원에게 전송합니다.
- AI 전송용 원본 피드백 메시지는 300자로 제한되어 있어 AI가 이를 기반으로 더 긴 문장을 생성할 가능성이 있습니다.  
이에 따라, 최종적으로 전송되는 피드백 메시지의 최대 길이를 600자로 제한하였습니다.
1. **잘못된 대상에게 피드백을 보낼 수 없음**
- 본인에게 피드백을 전송할 수 없음
- 같은 프로젝트에 속하지 않은 대상에게 피드백을 보낼 수 없음
2. **피드백 전송 제한**
- 같은 스프린트에서 특정 대상에게 피드백은 한 번만 전송 가능
3. **잘못된 요청 처리**
- 스프린트가 존재하지 않는 경우
- 해당 프로젝트의 참여자가 아닌 경우
- 피드백을 받을 대상(프로젝트 참여자)이 존재하지 않는 경우
=> feat: 피드백 메시지 전송 기능 구현

src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java, src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java, src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepository.java, src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryCustom.java, src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryImpl.java, src/main/java/com/amcamp/domain/feedback/domain/Feedback.java, src/main/java/com/amcamp/domain/feedback/dto/response/FeedbackInfoResponse.java, src/main/java/com/amcamp/global/exception/errorcode/FeedbackErrorCode.java, src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java, src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
- close #115 
---
- 특정 프로젝트 ID를 기반으로 로그인된 사용자가 해당 프로젝트에서 받은 피드백 메시지를 조회할 수 있도록 변경하였습니다.
- 기존 projectParticipantId를 요청값으로 받던 방식을 제거하고, 백엔드에서 projectId 기반으로 현재 사용자의 프로젝트 참여자를 조회하도록 수정하였습니다.
- 페이지네이션을 적용하여 이전 페이지의 마지막 feedbackId를 기준으로 조회할 수 있습니다.
1. **조회 권한 검증**
- 로그인된 사용자가 해당 프로젝트의 참여자가 아닌 경우 조회 불가
- 요청한 스프린트가 해당 프로젝트에 속하지 않으면 조회할 수 없음
2. **데이터 검증**  
- 해당 스프린트에서 받은 피드백이 없는 경우 예외 발생
- 존재하지 않는 프로젝트 참여자 ID 또는 스프린트 ID 요청 시 예외 발생
✔ 정상적인 피드백 조회 테스트 (projectId 기반 조회)
✔ 예외 발생 케이스 검증 (프로젝트 참여자 아님, 데이터 없음, 존재하지 않는 ID 요청 등)
=> feat: 피드백 메시지 조회 기능 구현

src/main/java/com/amcamp/domain/project/dto/response/ProjectParticipantInfoResponse.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #124 
---
- 프로젝트 참가자 응담 필드를 수정했습니다.
- id/nickname/profile/role
- 기존 프로젝트 참가자의 memberId로 검증했던 테스트 로직들을 nickname(member nickname과 동일)을 사용하도록 수정했습니다.
---
-
=> refactor: 프로젝트 참가자 응답 필드 수정

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/domain/Project.java, src/main/java/com/amcamp/domain/project/domain/ToDoInfo.java, src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java, src/main/java/com/amcamp/domain/project/dto/request/ProjectTodoInfoUpdateRequest.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintToDoUpdateRequest.java, src/main/java/com/amcamp/global/exception/errorcode/GlobalErrorCode.java, src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java, src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java, src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java, src/test/java/com/amcamp/domain/meeting/MeetingServiceTest.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #122
---
- 프로젝트 및 스프린트 생성 시, 시작 날짜가 현재 날짜로 자동 설정되도록 변경하였습니다.
- ToDoInfo 객체를 정적 팩토리 메서드를 통해 생성할 때, 시작 날짜를 LocalDate.now()로 설정합니다.
- 프로젝트 및 스프린트 일정 수정 시, 시작 날짜를 요청에서 제외하였습니다.
- 시작 날짜는 생성 시 현재 날짜로 설정되며, 이후 수정할 수 없습니다.
- 마감 날짜는 기존 시작 날짜보다 이전으로 설정할 수 없도록 검증을 추가하였습니다.
- 스프린트의 경우, 마감 날짜를 프로젝트 마감 날짜 이후로 수정할 수 없도록 제한하였습니다.
=> refactor: 프로젝트, 스프린트 생성 시 시작 날짜를 현재 날짜로 설정되도록 변경

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustom.java, src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectListInfoResponse.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
…n 응답필드 추가
- close #127 
---
- 기존 필터 조건을 통해 분리된 API를 통합하고, isParticipant 필드를 통해 Front UI 처리를 보다 용이하게 했습니다.
- isAdmin 필드를 추가하여 팀장 권한을 가지고 참여중인 프로젝트를 조회 즉시 확인할 수 있도록 했습니다.
---
-
=> refactor: 프로젝트 목록 조회 시 Admin 표시

src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java, src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #120 
---
- 스프린트 삭제 버그 수정
- 스프린트 삭제 시 연관된 피드백도 함께 삭제되도록 orphanRemoval 설정을 추가하였습니다.
- 스프린트 생성 버그 수정
- 기존 스프린트가 종료되지 않은 상태에서 새로운 스프린트가 생성되지 않도록 수정하였습니다.
- 스프린트 첫 생성이라면 정상적으로 생성됩니다.
- 진행 중인 스프린트가 있는 경우 마감일 이후로만 스프린트를 생성할 수 있습니다.
- ex) 25년 5월 20일에 끝나는 스프린트의 경우 5월 21일부터 스프린트 생성 허용
=> fix: 기존 스프린트가 종료되지 않은 상태에서 새로운 스프린트가 생성되는 문제 수정 

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustom.java, src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java, src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #118
---
- 프로젝트 참가자 목록 조회
- API를 기존 List 반환 방식에서 페이지네이션 방식으로 변경했습니다.
- 또한, 기존에는 프로젝트 참가자만 목록을 조회할 수 있었으나 이제 팀 참가자도 프로젝트 참가자 목록을 조회할 수 있도록 수정했습니다.
- 프로젝트 내 개인 참가자 정보 조회
- API가 더욱 명확하도록 스키마 설명을 수정했습니다.
---
- 프로젝트 참가자 테스트 코드의 경우 현재 멤버로 검증하고 있어서 이 부분 나중에 프로젝트 참가자로 리팩토링해야 할 듯 합니다!
=> refactor: 프로젝트 참가자 목록 조회 API 페이지네이션 적용

src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java, src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #120 
---
- 스프린트 삭제 버그 수정
- 스프린트 삭제 시 연관된 피드백도 함께 삭제되도록 orphanRemoval 설정을 추가하였습니다.
- 스프린트 생성 버그 수정
- 기존 스프린트가 종료되지 않은 상태에서 새로운 스프린트가 생성되지 않도록 수정하였습니다.
- 스프린트 첫 생성이라면 정상적으로 생성됩니다.
- 진행 중인 스프린트가 있는 경우 마감일 이후로만 스프린트를 생성할 수 있습니다.
- ex) 25년 5월 20일에 끝나는 스프린트의 경우 5월 21일부터 스프린트 생성 허용
=> fix: 기존 스프린트가 종료되지 않은 상태에서 새로운 스프린트가 생성되는 문제 수정

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepositoryCustom.java, src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepositoryImpl.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectRegisterDetailResponse.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #143 
---
- 프로젝트 참여 신청 목록 조회 시 requester의 팀 참여자 ID와 회원 닉네임, 회원 프로필 이미지를 함께 조회할 수 있도록 수정했습니다. 
- 기존 ProjectRegisterationInfoResponse 대신 ProjectRegisterDetailResponse를 새롭게 만들어 반환하도록 하였습니다. 
---
=> feat: 프로젝트 가입 신청 목록 조회 시 request의 닉네임과 프로필 함께 조회

src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java, src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java, src/main/java/com/amcamp/global/exception/errorcode/FeedbackErrorCode.java, src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
- close #145 
---
- 프로젝트에서 나간 사용자(Unknown)에게는 피드백을 전송할 수 없도록 처리하였습니다.
=> fix: 프로젝트에서 나간 사용자(Unknown)에게 피드백 전송이 불가능하도록 수정

src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java, src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
- close #129  
---
- 스프린트 수정 시 이후에 진행 중인 스프린트가 있을 경우 그 시작일 이전까지만 마감일을 설정할 수 있도록 검증을 추가하였습니다.
- 수정 대상 스프린트 이후에 시작되는 다른 스프린트가 있는지 확인합니다.
- 이후 스프린트가 없으면 제한 없이 수정 가능합니다.
=> fix: 스프린트 수정 시 마감일을 다음 스프린트 시작일 이후로 설정할 수 없도록 수정

src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java, src/main/java/com/amcamp/domain/sprint/dto/response/SprintDetailResponse.java, src/main/java/com/amcamp/domain/task/api/TaskController.java, src/main/java/com/amcamp/domain/task/dto/response/TaskBasicInfoResponse.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
- close #149 
---
- 기존 <스프린트 목록 조회> 메소드와 <태스크 목록 조회> 메소드를 합쳐 스프린트 목록 조회 시 태스크 목록도 포함하여 반환하는 메소드를 구현하였습니다. 
- 프로젝트별 스프린트 목록 조회에서는 스프린트에 속한 모든 태스크를, 개인별 스프린트 목록 조회에서는 회원이 담당한 모든 태스크를 반환합니다. 
---
-
=> feat: 스프린트와 태스크 조회 기능 구현 

src/main/java/com/amcamp/domain/project/dto/request/ProjectBasicInfoUpdateRequest.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #159 
---
- 프로젝트 기본 정보 수정 Request Dto에서 더 이상 사용되지 않는 goal 필드가 남아있어 제거하였습니다.
=> refactor: 프로젝트 기본 정보 수정 Request Dto에서 goal 필드 제거

src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java, src/main/java/com/amcamp/domain/sprint/dto/response/SprintDetailResponse.java, src/main/java/com/amcamp/domain/task/api/TaskController.java, src/main/java/com/amcamp/domain/task/dto/response/TaskBasicInfoResponse.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
- close #149 
---
- 기존 <스프린트 목록 조회> 메소드와 <태스크 목록 조회> 메소드를 합쳐 스프린트 목록 조회 시 태스크 목록도 포함하여 반환하는 메소드를 구현하였습니다.
- 프로젝트별 스프린트 목록 조회에서는 스프린트에 속한 모든 태스크를, 개인별 스프린트 목록 조회에서는 회원이 담당한 모든 태스크를 반환합니다.
---
-
=> feat: 스프린트 & 태스크 조회 기능 구현 

src/main/java/com/amcamp/domain/team/api/TeamController.java, src/main/java/com/amcamp/domain/team/application/TeamService.java, src/main/java/com/amcamp/domain/team/domain/Team.java, src/main/java/com/amcamp/domain/team/dto/request/TeamEmojiUpdateRequest.java, src/main/java/com/amcamp/domain/team/dto/request/TeamUpdateRequest.java, src/test/java/com/amcamp/domain/team/TeamServiceTest.java
- close #162 
---
- 팀 이름, 설명, 이모지를 수정하는 메소드를 하나로 통합하였습니다. 
- 팀 이름, 설명, 이모지는 모두 공백문자와 null을 허용합니다. 
- 공백문자와 null을 기입하거나 해당 필드가 request dto에 존재하지 않을 시 해당 필드는 수정되지 않고 기존 값을 유지합니다. 
---
=> fix: 팀 정보 수정 메소드 수정

src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintPagingDirection.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java, src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
- close #168 
---
- 양방향 페이징 구조 적용
- 기존 lastSprintId 기반 단방향 페이징 → baseSprintId, direction 기반 양방향 페이징으로 개선
- SprintPagingDirection enum(NEXT, PREV) 도입
- baseSprintId와 direction 중 하나만 전달된 경우 예외 처리
- 공통 로직 메서드 분리 (fetchSprintList, convertToSprintDetails)
- 쿼리 및 로직 리팩토링
- 페이징 방향에 따른 정렬 및 조건 처리 로직 리팩토링
- 태스크 조회 쿼리 메서드 리팩토링 (`fetchTaskListWithCondition` 도입으로 중복 제거)
=> fix: 스프린트 페이징 방향 처리 누락으로 인한 목록 조회 오류 수정

docker-compose.yml, nginx/default.conf
- close #156 
---
- Docker 네트워크를 기존 host 모드에서 bridge 모드로 변경했습니다.
- host 모드는 컨테이너가 호스트 네트워크를 그대로 사용하는 구조라 접근은 빠르지만  
컨테이너 간 네트워크가 격리되지 않아 보안이나 확장성 측면에서 제약이 있었습니다.   
서비스 구성을 더 명확하게 관리하고 향후 인프라 확장에도 유리하도록 bridge 모드로 전환했습니다.
- bridge 모드에서는 컨테이너 간 통신 시 localhost가 아닌 서비스 이름을 사용해야 하므로 
Nginx 설정에서 proxy_pass 대상을 localhost에서 backend로 수정했습니다.
=> refactor: Docker 네트워크 모드 bridge로 변경

src/main/java/com/amcamp/domain/task/application/TaskService.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #174 
---
- 태스크 진행상황별로 수정/삭제 권한을 부여합니다.
- 태스크가 NOT_STARTED, ON_GOING 상태일 경우 수정/삭제가 가능하지만 COMPLETED일 경우 불가능합니다. 
---
-
=> fix: 태스크 진행상태별 수정 삭제 권한 부여

src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectInfoResponse.java, src/main/java/com/amcamp/domain/sprint/dto/response/SprintProgressResponse.java
- close #179 
---
- projectInfoResponse 에 TeamName필드를 추가하였습니다.
- 추후 별도 API 를 통해 Team 객체의 다른 데이터 필요할 시 Id 포함하도록 수정하겠습니다.
---
-
=> refactor: 프로젝트 단일 조회 API 응답 필드에 팀명 포함하도록 수정

src/main/java/com/amcamp/domain/contribution/dto/response/BasicContributionInfoResponse.java, src/main/java/com/amcamp/domain/contribution/dto/response/ContributionInfoResponse.java, src/main/java/com/amcamp/domain/meeting/dto/request/MeetingCreateRequest.java, src/main/java/com/amcamp/domain/meeting/dto/request/MeetingTitleUpdateRequest.java, src/main/java/com/amcamp/domain/member/dto/request/NicknameUpdateRequest.java, src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java, src/main/java/com/amcamp/domain/project/dto/request/ProjectUpdateRequest.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java, src/main/java/com/amcamp/domain/task/api/TaskController.java, src/main/java/com/amcamp/domain/task/application/TaskService.java, src/main/java/com/amcamp/domain/task/dao/TaskRepositoryCustom.java, src/main/java/com/amcamp/domain/task/dao/TaskRepositoryImpl.java, src/main/java/com/amcamp/domain/task/dto/request/TaskBasicInfoUpdateRequest.java, src/main/java/com/amcamp/domain/task/dto/request/TaskCreateRequest.java, src/main/java/com/amcamp/domain/task/dto/response/TaskInfoResponse.java, src/main/java/com/amcamp/domain/team/dto/request/TeamCreateRequest.java, src/main/java/com/amcamp/domain/team/dto/request/TeamUpdateRequest.java, src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #192 
---
- TaskRepositoryImpl의 에서 member를 Join하지 못하여 발생했던 NPE를 해결하였습니다.
- 팀/프로젝트/태스크/미팅 생성 또는 수정 시 이름과 설명 글자수를 제한했습니다. 
- 프로젝트참가자 ID와 연관되어있지만 memberId로 작성되어있던 부분을 projectParticipantId로 수정하였습니다. 
---
-
=> fix: 스프린트 내 태스크가 조회되지 않을 경우 예외 처리 & 팀/프로젝트/태스크 명 글자수 제한 

src/main/java/com/amcamp/domain/project/application/ProjectService.java
- close #196 
---
- 기존에 프로젝트 팀장 권한 양도를 위해 필요했던 memberId 파라미터를 projectParticipantId로 변경합니다.
---
-
=> refactor: ProjectAdmin 변경 로직 요청 파라미터 수정

src/main/java/com/amcamp/domain/project/application/ProjectService.java
- close #202 
---
- 기존 projectParticipant 등록 정보가 존재할 때 신규 가입 요청 생성이 불가능했던 로직을, Active 상태인 경우에만 불가능하도록 수정했습니다.
---
-
=> refactor: Project 가입 신청 시 status inactive 인 경우 요청 보내기 허용

src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepository.java, src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #Issue_number
---
- DB에 중복 칼럼 있을 시 첫번쨰 registration 반환하도록 디버깅
---
-
=> bug: DB에 중복 칼럼 있을 시 첫번쨰 registration 반환하도록 디버깅

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #213
---
- projectRegistration 삭제 요청 파라미터 및 내부 로직 수정
- 기존 프로젝트 가입신청 객체의 id 를 직접 요청 파라미터로 받았던 방식에서, 프로젝트 id 와 인증된 유저의 id를 통해 삭제할 수 있도록 로직을 개선하였습닏다.
---
-
=> refactor: Project 가입 신청 취소 필요 파라미터 수정

src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java, src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java, src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryCustom.java, src/main/java/com/amcamp/domain/feedback/dao/FeedbackRepositoryImpl.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectParticipantFeedbackInfoResponse.java, src/test/java/com/amcamp/domain/feedback/application/FeedbackServiceTest.java
- close #212 
---
- 스프린트별 참가자 목록을 반환하면서 동료 평가 여부를 feedbackStatus로 반환하게 하였습니다.
- 접속 중인 회원 본인과 아직 동료평가를 받지 않은 회원은 PENDING, 동료평가를 받은 회원은 COMPLETED 상태로 반환됩니다. 
---
-
=> feat: 스프린트별 참가자 목록 & 동료 평가 여부 반환 메소드
