AM-Inspire-Devfit/devfit-server

build.gradle, src/main/java/com/amcamp/domain/HealthController.java, src/main/java/com/amcamp/global/config/SwaggerConfig.java
- close #5 
---
- Swagger Config 생성
- Swagger 테스트를 위한 Health Check API 구현
---
- 인가/인증 구현 시 Swagger에 JWT 추가 설정 필요
=> chore: Swagger 설정

build.gradle, src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java, src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
- close #12 
---
- Spring Security 기본 설정을 추가하였습니다.
- CSRF 비활성화
- CORS 설정
- 임시로 모든 url 요청 허용
=> chore: Spring Security 설정

.github/workflows/develop_deploy.yml, Dockerfile, build.gradle
- close #16 
---
- plain.jar 생성 비활성화
- workflow에서 Docker 이미지 빌드를 위한 Dockerfile 생성
- 개발 서버 CI/CD workflow 생성
=> chore: CI/CD 파이프라인 구축

.github/workflows/develop_build_deploy.yml, .github/workflows/develop_deploy.yml, docker-compose.yml
- close #21 
---
- 도커 컴포즈 파일을 작성하였습니다.
- 프로젝트의 루트 디렉토리에는 docker-compose.yml 파일이 존재하며 이를 통해 컨테이너를 관리합니다.
- deploy 액션이 실행되면 scp-action이 작동하여 해당 파일을 EC2 (/home/ubuntu)로 복사합니다.
- 복사된 파일을 기반으로 docker compose up이 실행되어 컨테이너가 구동됩니다.
=> chore: Docker Compose 적용

build.gradle, src/main/java/com/amcamp/global/config/querydsl/QueryDslConfig.java
- close #41 
---
- Querydsl 설정을 추가하였습니다.
- querydsl 의존성 추가
- querydsl config 추가
- 빌드 시 build/generated 경로에 q 클래스가 생성됩니다.
=> chore: Querydsl 설정

src/main/java/com/amcamp/domain/project/domain/Project.java, src/main/java/com/amcamp/domain/project/domain/ToDoInfo.java, src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectInfoResponse.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/domain/task/domain/Task.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #79 
---
- Project/Sprint/Task 엔티티의 LoaclDateTime 필드 -> LocalDate 타입으로 수정
- ProjectInfoRequestDto 내 JsonProperty 명시 어노테이션 제거
---
-
=> refactor: LocalDateTime 타입 LocalDate 변경 및 JsonProperty 어노테이션 제거

src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java, src/main/java/com/amcamp/domain/team/application/TeamService.java, src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java, src/main/java/com/amcamp/global/exception/errorcode/TeamErrorCode.java, src/test/java/com/amcamp/domain/team/TeamServiceTest.java
- close #71 
---
- 스프린트 생성 기능을 구현하였습니다.
- 프로젝트 참여자가 아닌 경우는 팀 참여자가 아닌 경우와 마찬가지로 HTTP 상태 코드를 404로 해두었는데, 적절한 상태 코드로 수정이 필요해보입니다.
---
- 스프린트 생성 테스트 코드는 수정과 삭제 작업 시에 추가해서 올리겠습니다~!
=> feat: 스프린트 생성 기능 구현

src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintBasicUpdateRequest.java, src/main/java/com/amcamp/domain/sprint/dto/request/SprintCreateRequest.java
- close #91 
---
- 스프린트 생성 시 title 요청값을 받지 않고 자동으로 번호를 지정하도록 변경
- 스프린트 수정 시 제목 변경을 허용하지 않도록 처리
- 스프린트 삭제 시 자동으로 번호를 재조정하여 순서 유지
=> refactor: 스프린트 제목에 번호가 자동으로 지정되도록 변경

src/main/java/com/amcamp/domain/task/api/TaskController.java, src/main/java/com/amcamp/domain/task/application/TaskService.java, src/main/java/com/amcamp/domain/task/domain/SOSStatus.java, src/main/java/com/amcamp/domain/task/domain/Task.java, src/main/java/com/amcamp/domain/task/dto/response/TaskInfoResponse.java, src/main/java/com/amcamp/global/exception/errorcode/TaskErrorCode.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #97 
---
- task 내 sos status (SOS, NOT_SOS) 필드를 추가했습니다. 
- sos 메소드 호출 시 상태가 SOS로 변경됩니다. 아직 할당 받지 않은 task의 경우 예외처리로 인해 호출이 불가능합니다. 
- task 할당 메소드 호출 시 sos 상태와 assignee, project 팀장을 모두 검증하여 예외처리 했습니다. 
---
-
=> feat: sos 기능 구현 & 관련 태스크 메소드 수정 

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectParticipantRepository.java, src/main/java/com/amcamp/domain/project/domain/ProjectParticipant.java, src/main/java/com/amcamp/domain/project/domain/ProjectParticipantRole.java, src/main/java/com/amcamp/domain/project/dto/request/ProjectAdminChangeRequest.java, src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
- close #70 
---
- 프로젝트 나가기 구현(프로젝트 참여자 삭제)
- 프로젝트 삭제 구현(프로젝트 삭제 및 연관된 프로젝트 참여자 삭제)
---
-
=> feat: 프로젝트 삭제/나가기 구현

src/main/java/com/amcamp/domain/feedback/api/FeedbackController.java, src/main/java/com/amcamp/domain/feedback/application/ChatGptService.java, src/main/java/com/amcamp/domain/feedback/application/FeedbackService.java, src/main/java/com/amcamp/domain/feedback/dto/Choice.java, src/main/java/com/amcamp/domain/feedback/dto/Message.java, src/main/java/com/amcamp/domain/feedback/dto/request/ChatRequest.java, src/main/java/com/amcamp/domain/feedback/dto/request/OriginalFeedbackRequest.java, src/main/java/com/amcamp/domain/feedback/dto/response/ChatResponse.java, src/main/java/com/amcamp/domain/feedback/dto/response/FeedbackRefineResponse.java, src/main/java/com/amcamp/global/config/feign/FeignConfig.java, src/main/java/com/amcamp/infra/config/feign/OpenAiClient.java, src/main/java/com/amcamp/infra/config/openai/OpenAiProperties.java, src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java, src/main/resources/application-openai.yml, src/main/resources/application.yml
- close #99 
---
- OpenAI를 사용하여 사용자가 입력한 피드백 메시지를 개선하는 기능을 구현하였습니다.
- 입력된 피드백이 부정적이거나 공격적인 표현을 포함할 경우 본래의 의미를 유지하면서 더 부드럽고 건설적인 표현으로 변환합니다.
- 프롬프트를 통해 OpenAI가 피드백을 개선할 수 있도록 가이드하였으며 예제 변환 사례를 포함하여 보다 자연스러운 결과가 나오도록 조정하였습니다.
- 피드백 메시지는 최대 300자로 제한하였습니다.
=> feat: OpenAI 기반 피드백 메시지 개선

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepository.java, src/main/java/com/amcamp/domain/project/domain/Project.java, src/main/java/com/amcamp/domain/project/domain/ProjectParticipant.java, src/main/java/com/amcamp/domain/project/domain/ProjectParticipantUnknown.java, src/main/java/com/amcamp/domain/project/domain/ProjectRegistration.java, src/main/java/com/amcamp/domain/project/domain/ProjectRegistrationStatus.java, src/main/java/com/amcamp/domain/project/dto/request/ProjectCreateRequest.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectInfoResponse.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectListInfoResponse.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectParticipantInfoResponse.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectRegistrationInfoResponse.java, src/main/java/com/amcamp/global/exception/errorcode/ProjectErrorCode.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #94  
---
- 프로젝트 가입 신청 로직을 구현
- 프로젝트 가입 신청 목록 구현
- Admin 의 승인/거부 로직을 구현
- 프로젝트 가입 신청 취소 로직 구현
- 프로젝트 참여자 조회 로직 구현(본인 정보)
- 프로젝트 참여자 전체 목록 조회 로직 구현
---
-
=> feat: 프로젝트 가입/참여자 조회 구현

src/main/java/com/amcamp/domain/project/api/ProjectController.java, src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryCustom.java, src/main/java/com/amcamp/domain/project/dao/ProjectRepositoryImpl.java, src/main/java/com/amcamp/domain/project/dto/response/ProjectListInfoResponse.java, src/test/java/com/amcamp/domain/project/ProjectServiceTest.java
Reverts AM-Inspire-Devfit/devfit-server#133
=> revert: 프로젝트 목록 조회 시 Admin 표시

src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepository.java, src/main/java/com/amcamp/domain/sprint/domain/Sprint.java, src/main/java/com/amcamp/global/exception/errorcode/SprintErrorCode.java, src/test/java/com/amcamp/domain/contribution/ContributionServiceTest.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
Reverts AM-Inspire-Devfit/devfit-server#131
=> revert: 기존 스프린트가 종료되지 않은 상태에서 새로운 스프린트가 생성되는 문제 수정

.github/workflows/develop_build_deploy.yml, docker-compose.yml, nginx/default.conf, src/main/java/com/amcamp/global/common/constants/UrlConstants.java, src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java, src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java
- close #134 
---
Spring 서버에 HTTPS 적용을 위해 ELB(ACM 인증서)와 Nginx 리버스 프록시를 활용한 구조로 설정을 구성했습니다.
- Nginx 도입
- default.conf 설정 파일 추가
- docker-compose에 Nginx 컨테이너 추가
- CI/CD 워크플로 수정
- Nginx 컨테이너 실행 및 설정 반영을 위한 reload 명령 추가
- Swagger 설정
- 프로파일(dev, local 등)에 따라 Swagger 서버 URL 동적 설정
- CORS 설정
- 개발 환경에서 필요한 도메인만 허용
=> chore: Nginx 리버스 프록시 도입 및 HTTPS 적용

src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java, src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java, src/main/java/com/amcamp/global/helper/SpringEnvironmentHelper.java
- close #141 
---
- 각 환경별 설정 값을 동적으로 할당할 수 있도록 SpringEnvironmentHelper를 도입했습니다.
- 현재는 DEV, LOCAL 환경만 존재하지만 추후 운영 환경 추가 시 PROD 처리 로직도 함께 반영할 예정입니다.
=> chore: SpringEnvironmentHelper 도입

src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java, src/main/resources/application-dev.yml
- close #147 
---
- 서버 배포 시마다 데이터가 초기화되는 문제를 방지하고자, ddl-auto 설정을 update로 변경하였습니다.
=> chore: 개발 환경 ddl-auto 설정 변경

src/main/java/com/amcamp/domain/project/api/ProjectController.java
- close #157 
---
- 프로젝트 삭제 api 의 uri를 기존 "/{projectId}/" 에서 "/{projectId}"로 수정하여, 불필요한 슬래쉬를 제거합니다
---
-
=> refactor: project 삭제 uri 수정

.github/workflows/develop_build_deploy.yml, docker-compose.yml, nginx/default.conf
=> fix: Docker bridge 네트워크 전환 후 Nginx 502 에러 수정

src/main/java/com/amcamp/domain/task/application/TaskService.java, src/main/java/com/amcamp/global/exception/errorcode/TaskErrorCode.java, src/test/java/com/amcamp/domain/task/TaskServiceTest.java
- close #173 
---
- sos 후 본인에게 재할당하는 경우, 예외처리를 하였습니다. 
---
-
=> fix: 태스크 sos 후 본인 할당 문제 수정

.github/workflows/production_build_deploy.yml, src/main/java/com/amcamp/global/common/constants/UrlConstants.java, src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java, src/main/java/com/amcamp/global/config/swagger/SwaggerConfig.java, src/main/java/com/amcamp/global/helper/SpringEnvironmentHelper.java, src/main/resources/application-prod.yml, src/main/resources/application.yml
- close #181 
---
- 운영 환경 설정 및 구성
- 운영 환경의 도메인과 서버 URL을 추가하였습니다.
- application-prod.yml 파일을 추가하여 운영 환경에 맞는 설정을 구성하였습니다.
- Swagger 인증
- Swagger 인증 방식을 운영 환경에 맞게 설정하고 CORS 도메인을 추가하였습니다.
- Swagger 인증 계정의 비밀번호를 암호화하여 평문으로 저장되지 않도록 처리하였습니다.
- WebSecurityConfig 클래스 수정
- InMemoryUserDetailsManager를 WebSecurityConfig 클래스 내로 이동시켜 Swagger 인증 관련 설정을 보다 명확하게 관리할 수 있도록 수정하였습니다.
- 운영 환경 workflow 추가
- 운영 환경에서 사용할 workflow를 추가하였습니다.
=> feat: 운영 환경 구성

src/main/java/com/amcamp/global/util/CookieUtil.java
- close #183 
---
- 운영 환경에서 쿠키의 SameSite 속성을 Strict로 변경하였습니다.
- 개발 및 운영 환경에서 쿠키의 Secure 속성을 true로 변경하였습니다.
=> refactor: 개발 및 운영 환경에서 쿠키 설정 변경

src/main/java/com/amcamp/global/util/CookieUtil.java
- close #185 
---
- 로컬 환경에서의 API 연동 작업을 위해 일시적으로 CORS 설정을 해제합니다.
---
-
=> refactor: 쿠키 CORS 세팅 임시 완화

src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java, src/main/java/com/amcamp/global/util/CookieUtil.java
Reverts AM-Inspire-Devfit/devfit-server#187
=> Revert "Refactor/185 cookie cors tmp"

src/main/java/com/amcamp/domain/meeting/dao/MeetingRepositoryImpl.java, src/main/java/com/amcamp/domain/meeting/dto/response/MeetingInfoResponse.java
- close #193 
---
- API 연동을 위해 팀 미팅 조회 응답 필드에 Id를 추가하였습니다.
---
-
=> refactor: 팀 미팅 조회 응답 필드에 Id 추가 

src/main/java/com/amcamp/domain/project/application/ProjectService.java, src/main/java/com/amcamp/domain/project/dao/ProjectRegistrationRepository.java
- close #200 
---
- projectRegistration 생성 시 팀 전체-> 프로젝트 해당하는 요청만 검증하도록 오류 수정
---
-
=> refactor: projectRegistration 생성 시 팀 전체-> 프로젝트 해당하는 요청만 검증하도록 오류 수정

src/main/java/com/amcamp/domain/project/domain/ProjectRegistration.java
- close #208 
---
- 프로젝트 참가 내 칼럼을 잘못 참조하고 있어 수정하였습니다. 
---
-
=> fix: 프로젝트 참가 칼럼명 수정

src/main/java/com/amcamp/domain/sprint/api/SprintController.java, src/main/java/com/amcamp/domain/sprint/application/SprintService.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryCustom.java, src/main/java/com/amcamp/domain/sprint/dao/SprintRepositoryImpl.java, src/main/java/com/amcamp/domain/sprint/dto/response/SprintIdResponse.java, src/test/java/com/amcamp/domain/sprint/application/SprintServiceTest.java
- close #210 
---
- 프로젝트 내 스프린트 아이디 목록 조회 기능을 구현합니다. 
---
-
=> feat: 프로젝트별 스프린트 아이디 목록 조회 기능

src/main/java/com/amcamp/domain/project/api/ProjectController.java
- close #213
---
- api 요청 파라미터 수정
---
-
=> refactor: Project 가입신청 api 요청 파라미터 수정

src/main/resources/application.yml
- close #220 
---
- prod 환경 profile group 추가
=> fix: prod 환경에서 profile group 누락으로 설정 미적용 수정
